In [2]:
#This notebook is written using google colab
import pandas as pd

In [3]:
file_path='/content/retail_analytics_20k.csv.xls'

In [4]:
df=pd.read_csv(file_path)
df

,order_id,order_date,year,month,month_name,quarter,customer_id,customer_segment,age_group,gender,...,unit_price_egp,discount_pct,revenue_egp,cost_egp,profit_egp,profit_margin,delivery_days,customer_rating,returned,website_visits_before_purchase
0,ORD-000001,2025-10-16,2025,10,October,Q4,CUST-02941,Student,18-24,Male,...,344.09,0.0352,331.99,267.56,64.43,0.1941,3,4.9,No,6
1,ORD-000002,2025-09-10,2025,9,September,Q3,CUST-01402,Young Professional,25-34,Female,...,9965.76,0.1205,8764.93,6550.45,2214.48,0.2527,1,4.0,No,2
2,ORD-000003,2024-09-07,2024,9,September,Q3,CUST-03272,Premium,35-44,Male,...,1012.73,0.0973,3656.69,1950.83,1705.86,0.4665,2,4.8,No,0
3,ORD-000004,2024-08-12,2024,8,August,Q3,CUST-02158,Young Professional,25-34,Male,...,6644.60,0.0616,24940.68,19540.87,5399.81,0.2165,0,3.5,Yes,0
4,ORD-000005,2024-07-01,2024,7,July,Q3,CUST-04418,Premium,45-54,Male,...,1225.89,0.0000,2451.78,1835.73,616.05,0.2513,1,5.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,ORD-019996,2025-09-09,2025,9,September,Q3,CUST-02548,Family,35-44,Female,...,2172.80,0.0769,2005.75,1191.10,814.65,0.4062,1,4.7,No,5
19996,ORD-019997,2025-06-26,2025,6,June,Q2,CUST-00626,Premium,45-54,Female,...,1596.46,0.0000,4789.38,2483.12,2306.26,0.4815,1,4.1,No,4
19997,ORD-019998,2025-01-11,2025,1,January,Q1,CUST-03102,Family,25-34,Female,...,3310.70,0.0716,12294.49,7814.45,4480.04,0.3644,5,4.3,No,2
19998,ORD-019999,2025-06-15,2025,6,June,Q2,CUST-03543,Premium,45-54,Female,...,75840.11,0.0000,75840.11,55767.40,20072.71,0.2647,2,3.9,No,5
19999,ORD-020000,2024-06-17,2024,6,June,Q2,CUST-03783,Student,25-34,Male,...,21087.53,0.0718,19574.42,15891.78,3682.64,0.1881,3,4.7,No,6

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   order_id                        20000 non-null  object
 1   order_date                      20000 non-null  object
 2   year                            20000 non-null  int64
 3   month                           20000 non-null  int64
 4   month_name                      20000 non-null  object
 5   quarter                         20000 non-null  object
 6   customer_id                     20000 non-null  object
 7   customer_segment                20000 non-null  object
 8   age_group                       20000 non-null  object
 9   gender                          20000 non-null  object
 10  country                         20000 non-null  object
 11  region                          20000 non-null  object
 12  city                            20000 non-null  object
 13  sales_channel                   20000 non-null  object
 14  traffic_source                  20000 non-null  object
 15  category                        20000 non-null  object
 16  sub_category                    20000 non-null  object
 17  product_name                    20000 non-null  object
 18  payment_method                  20000 non-null  object
 19  shipping_method                 20000 non-null  object
 20  campaign                        20000 non-null  object
 21  quantity                        20000 non-null  int64
 22  unit_price_egp                  20000 non-null  float64
 23  discount_pct                    20000 non-null  float64
 24  revenue_egp                     20000 non-null  float64
 25  cost_egp                        20000 non-null  float64
 26  profit_egp                      20000 non-null  float64
 27  profit_margin                   20000 non-null  float64
 28  delivery_days                   20000 non-null  int64
 29  customer_rating                 20000 non-null  float64
 30  returned                        20000 non-null  object
 31  website_visits_before_purchase  20000 non-null  int64
dtypes: float64(7), int64(5), object(20)
memory usage: 4.9+ MB

,year,month,quantity,unit_price_egp,discount_pct,revenue_egp,cost_egp,profit_egp,profit_margin,delivery_days,customer_rating,website_visits_before_purchase
count,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,2024.502600,6.543900,1.83445,6949.031827,0.067510,9529.288511,6652.357933,2876.930577,0.378106,3.095000,4.227865,2.485350
std,0.500006,3.433914,1.13838,11266.315666,0.054409,16088.383512,12546.068889,3804.988823,0.107512,2.466836,0.579635,2.138835
min,2024.000000,1.000000,1.00000,42.770000,0.000000,41.330000,18.610000,19.310000,0.160000,0.000000,1.300000,0.000000
25%,2024.000000,4.000000,1.00000,1099.825000,0.023300,1663.007500,970.612500,641.380000,0.282200,1.000000,3.900000,1.000000
50%,2025.000000,7.000000,1.00000,2868.175000,0.058000,4137.435000,2466.975000,1618.580000,0.397700,2.000000,4.300000,2.000000
75%,2025.000000,10.000000,2.00000,6844.855000,0.101900,10439.295000,6615.635000,3670.207500,0.463300,5.000000,4.700000,4.000000
max,2025.000000,12.000000,6.00000,98053.220000,0.287500,264466.610000,218784.560000,61981.300000,0.579900,8.000000,5.000000,13.000000

In [6]:
df.isna()
df.isna().sum()

order_id                          0
order_date                        0
year                              0
month                             0
month_name                        0
quarter                           0
customer_id                       0
customer_segment                  0
age_group                         0
gender                            0
country                           0
region                            0
city                              0
sales_channel                     0
traffic_source                    0
category                          0
sub_category                      0
product_name                      0
payment_method                    0
shipping_method                   0
campaign                          0
quantity                          0
unit_price_egp                    0
discount_pct                      0
revenue_egp                       0
cost_egp                          0
profit_egp                        0
profit_margin                     0
delivery_days                     0
customer_rating                   0
returned                          0
website_visits_before_purchase    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [10]:
df_cleaned=df
df_cleaned['order_date']=pd.to_datetime(df_cleaned['order_date'])
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   order_id                        20000 non-null  object
 1   order_date                      20000 non-null  datetime64[ns]
 2   year                            20000 non-null  int64
 3   month                           20000 non-null  int64
 4   month_name                      20000 non-null  object
 5   quarter                         20000 non-null  object
 6   customer_id                     20000 non-null  object
 7   customer_segment                20000 non-null  object
 8   age_group                       20000 non-null  object
 9   gender                          20000 non-null  object
 10  country                         20000 non-null  object
 11  region                          20000 non-null  object
 12  city                            20000 non-null  object
 13  sales_channel                   20000 non-null  object
 14  traffic_source                  20000 non-null  object
 15  category                        20000 non-null  object
 16  sub_category                    20000 non-null  object
 17  product_name                    20000 non-null  object
 18  payment_method                  20000 non-null  object
 19  shipping_method                 20000 non-null  object
 20  campaign                        20000 non-null  object
 21  quantity                        20000 non-null  int64
 22  unit_price_egp                  20000 non-null  float64
 23  discount_pct                    20000 non-null  float64
 24  revenue_egp                     20000 non-null  float64
 25  cost_egp                        20000 non-null  float64
 26  profit_egp                      20000 non-null  float64
 27  profit_margin                   20000 non-null  float64
 28  delivery_days                   20000 non-null  int64
 29  customer_rating                 20000 non-null  float64
 30  returned                        20000 non-null  object
 31  website_visits_before_purchase  20000 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(5), object(19)
memory usage: 4.9+ MB

In [13]:
egp = df_cleaned.groupby(['revenue_egp','cost_egp','profit_egp'])['profit_margin'].mean().reset_index()
egp

       revenue_egp   cost_egp  profit_egp  profit_margin
0            41.33      22.02       19.31         0.4672
1            41.35      18.61       22.74         0.5499
2            42.68      22.94       19.74         0.4625
3            44.03      22.96       21.07         0.4785
4            46.89      25.79       21.10         0.4500
...            ...        ...         ...            ...
19995    224647.78  174082.98    50564.80         0.2251
19996    227489.33  172439.57    55049.76         0.2420
19997    235205.90  176433.00    58772.90         0.2499
19998    236022.13  197308.35    38713.78         0.1640
19999    264466.61  218784.56    45682.05         0.1727

[20000 rows x 4 columns]

In [14]:
(egp < 0).any()

revenue_egp      False
cost_egp         False
profit_egp       False
profit_margin    False
dtype: bool

In [15]:
# Save DataFrame to CSV
df_cleaned.to_csv('sales_data.csv', index=False)